"""add ingestion jobs

Revision ID: e37cdcdf31dd
Revises: 9ed1e76d4c54
Create Date: 2026-09-23 01:39:33.594957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e37cdcdf31dd'
down_revision: Union[str, Sequence[str], None] = '9ed1e76d4c54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_lead_analysis_id'), 'lead_analysis', ['id'], unique=False)
    op.create_index(op.f('ix_lead_analysis_organization_id'), 'lead_analysis', ['organization_id'], unique=False)
    op.create_index(op.f('ix_leads_created_at'), 'leads', ['created_at'], unique=False)
    op.create_index(op.f('ix_leads_id'), 'leads', ['id'], unique=False)
    op.create_index(op.f('ix_leads_next_follow_up'), 'leads', ['next_follow_up'], unique=False)
    op.create_index('ix_leads_org_created', 'leads', ['organization_id', 'created_at'], unique=False)
    op.create_index('ix_leads_org_followup', 'leads', ['organization_id', 'next_follow_up'], unique=False)
    op.create_index('ix_leads_org_status', 'leads', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('ix_leads_organization_id'), 'leads', ['organization_id'], unique=False)
    op.create_index(op.f('ix_leads_status'), 'leads', ['status'], unique=False)
    op.drop_constraint(op.f('uq_organizations_slug'), 'organizations', type_='unique')
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.create_unique_constraint(op.f('uq_organizations_slug'), 'organizations', ['slug'])
    op.drop_index(op.f('ix_leads_status'), table_name='leads')
    op.drop_index(op.f('ix_leads_organization_id'), table_name='leads')
    op.drop_index('ix_leads_org_status', table_name='leads')
    op.drop_index('ix_leads_org_followup', table_name='leads')
    op.drop_index('ix_leads_org_created', table_name='leads')
    op.drop_index(op.f('ix_leads_next_follow_up'), table_name='leads')
    op.drop_index(op.f('ix_leads_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_created_at'), table_name='leads')
    op.drop_index(op.f('ix_lead_analysis_organization_id'), table_name='lead_analysis')
    op.drop_index(op.f('ix_lead_analysis_id'), table_name='lead_analysis')
    # ### end Alembic commands ###
