{
  "apiVersion": "v1",
  "kind": "List",
  "items": [
    {
      "apiVersion": "v1",
      "kind": "ServiceAccount",
      "metadata": {
        "name": "local-ingress"
      }
    },
    {
      "apiVersion": "rbac.authorization.k8s.io/v1",
      "kind": "Role",
      "metadata": {
        "name": "local-ingress"
      },
      "rules": [
        {
          "apiGroups": [
            ""
          ],
          "resources": [
            "services",
            "secrets"
          ],
          "verbs": [
            "get",
            "list",
            "watch"
          ]
        },
        {
          "apiGroups": [
            "discovery.k8s.io"
          ],
          "resources": [
            "endpointslices"
          ],
          "verbs": [
            "get",
            "list",
            "watch"
          ]
        },
        {
          "apiGroups": [
            "networking.k8s.io"
          ],
          "resources": [
            "ingresses"
          ],
          "verbs": [
            "get",
            "list",
            "watch"
          ]
        },
        {
          "apiGroups": [
            "networking.k8s.io"
          ],
          "resources": [
            "ingresses/status"
          ],
          "verbs": [
            "update"
          ]
        }
      ]
    },
    {
      "apiVersion": "rbac.authorization.k8s.io/v1",
      "kind": "RoleBinding",
      "metadata": {
        "name": "local-ingress"
      },
      "roleRef": {
        "apiGroup": "rbac.authorization.k8s.io",
        "kind": "Role",
        "name": "local-ingress"
      },
      "subjects": [
        {
          "kind": "ServiceAccount",
          "name": "local-ingress",
          "namespace": "leadforge-local"
        }
      ]
    }
  ]
}
