{
  "apiVersion": "kustomize.config.k8s.io/v1beta1",
  "kind": "Kustomization",
  "namespace": "leadforge-local",
  "resources": [
    "config.yaml",
    "postgres.yaml",
    "postgres-service.yaml",
    "backend-service.yaml",
    "frontend-service.yaml",
    "local-ingress-service.yaml",
    "ingress-rbac.yaml",
    "ingress-controller.yaml",
    "ingress.yaml"
  ],
  "configMapGenerator": [
    {
      "name": "leadforge-nginx",
      "files": [
        "nginx.conf",
        "security-headers.conf"
      ]
    }
  ],
  "generatorOptions": {
    "disableNameSuffixHash": true
  }
}
